name: berlin-scifi-bookclub-website
static_sites:
- build_command: rm -r ./public; hugo --destination ./public
  environment_slug: hugo
  github:
    branch: main
    deploy_on_push: true
    repo: ddevlin/berlin-scifi-bookclub-website
  name: berlin-scifi-bookclub-website